name            : example
description     : Example Project for cupertino_stackview.
version         : 1.0.6
author          : Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository      : https://github.com/aliyigitbireroglu/flutter-cupertino-stackview
homepage        : https://www.cosmossoftware.coffee

environment     :
  sdk: ">=2.2.2 <3.0.0"

dependencies    :
  flutter            :
    sdk: flutter
  cupertino_stackview:
    path: ../
  spring_button      : ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter         :
  uses-material-design: true
  assets              :
    - assets/
